# Generated by Django 4.2.7 on 2024-03-15 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('groceryapp', '0004_userprofile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
